interface TranslationEntry {
    [key: string]: string;
}
export interface Translations {
    [key: string]: TranslationEntry;
}

const appContext: Translations = {
    welcome: { en: "Welcome", he: "ברוכים הבאים", ar: "" },
    hello: { en: "Hello", he: "שלום", ar: "" },
    loading: { en: "Loading...", he: "טוען...", ar: "" },
    sign_out: { en: "Sign Out", he: "התנתק", ar: "" },
    next_page: { en: "Next Page", he: "לעמוד הבא", ar: "" },
    no_next_page: { en: "No Next Page", he: "אין עמוד הבא", ar: "" },
    prev_page: { en: "Previous Page", he: "לעמוד הקודם", ar: "" },
    no_prev_page: { en: "No Previous Page", he: "אין עמוד הקודם", ar: "" },
    back_to_main: { en: "Back to main room", he: "חזרה לחדר הראשי", ar: "" },
    success: { en: "Success!", he: "הצלחה!", ar: "" },
    wrong: { en: "Wrong answer... Try again", he: "טעות... נסו שוב", ar: "" },
    continue: { en: "Your getting there... Continue", he: "אתם בדרך הנכונה... המשיכו", ar: "" },
    finish: { en: "Finish", he: "לסיום", ar: "" },
    answer_quiz: { en: "Enter Quiz Answer", he: "מלא תשובה לחידה", ar: "" },
    close: { en: "Close", he: "סגירה", ar: "" },
    close_quiz: { en: "Close Quiz", he: "סגירת חידה", ar: "" },
    check_answer: { en: "Check Answer", he: "בדיקת התשובה", ar: "" },
    more_info: { en: "More Info", he: "מידע נוסף", ar: "" },
    phone_on_side: {
        en: "Please turn your phone on its side",
        he: "אנא סובבו את מכשיר הסלולארי שלכם על צידו",
        ar: "",
    },
    give_hint: { en: "Yes, please give me a hint...", he: "כן, אשמח לקבל רמז בבקשה...", ar: "" },
    hint: { en: "Hint", he: "רמז", ar: "" },
    get_hint: { en: "Get Hints", he: "קבלו רמזים", ar: "" },
    close_hint: { en: "Close Hints", he: "סגור רמזים", ar: "" },
    do_want_hint: { en: "Do you want a hint?", he: "האם תרצה/י רמז?", ar: "" },
    do_want_another_hint: { en: "Do you want another hint?", he: "האם תרצה/י רמז נוסף?", ar: "" },
    cant_help_more: {
        en: "Sorry, I can't help you any more...",
        he: "מחילה, לא אוכל לעזור לך יותר...",
        ar: "",
    },
    you_can_do_it: {
        en: "Try using the hints I already gave you. You can do it!!",
        he: "נסה להשתמש ברמזים שכבר נתתי לך. אתה יכול לעשות את זה!!",
        ar: "",
    },
    welcome_hint: {
        en: "Hello!! I can help you with the quiz?",
        he: "שלום! האם אוכל לעזור לך עם החידה?",
        ar: "",
    },
    prepare: { en: "Preparing Riddle", he: "מכין את החידה", ar: "" },
    leave_room: { en: "Leaving The Escape-Room", he: "עזב את החדר", ar: "" },
    are_you_sure: {
        en: "Are you sure you want to leave the escape-room?",
        he: "האם אתה בטוח שברצונך לעזוב את חדר הבריחה?",
        ar: "",
    },
    cancel: { en: "Cancel", he: "ביטול", ar: "" },
    exit_room: { en: "Exit Room", he: "יציאה מהחדר", ar: "" },
    enter_room: { en: "Enter Room", he: "כניסה לחדר", ar: "" },
    sexual_harassment: {
        en: "PreventingSexual Harassment",
        he: "מניעת הטרדות מיניות",
        ar: "",
    },
    first_aid: { en: "First Aid", he: "עזרה ראשונה", ar: "" },
    confirm: { en: "Confirm", he: "אישור", ar: "" },
    fraud: { en: "Embezzlement and fraud", he: "הונאות ומעילות", ar: "" },
    title: { en: "Educational Escape Rooms", he: "חדרי בריחה חינוכיים", ar: "" },
    correct: { en: "Correct ✔️", he: "✔️ נכון", ar: "✔️" },
    incorrect: { en: "Incorrect ❌", he: "❌ לא נכון", ar: "❌" },
    situationAction: {
        en: "Situation & Action",
        he: "מצב ופעולה",
        ar: "الوضع العمل",
    },
    instructions: {
        en: "Instructions: ",
        he: "הוראות: ",
        ar: "تعليمات: ",
    },
    puzzle6_inst: {
        en: "Arrange the images in the correct order",
        he: "סדרו את התמונות בסדר הנכון",
        ar: "",
    },
    room_finished: { en: "Room Completed!", he: "החדר הושלם!", ar: "" },
    new_room: { en: "New Room", he: "חדר חדש", ar: "" },
    subscription: { en: "Subscription", he: "מנוי", ar: "" },
    upgrade: { en: "Upgrade", he: "שדרג", ar: "" },
    edit_profile: { en: "Edit Profile", he: "ערוך פרופיל", ar: "" },
    last_updated: { en: "Last Updated", he: "עודכן לאחרונה", ar: "" },
    created_at: { en: "Date Created", he: "תאריך יצירה", ar: "" },
    build_room: { en: "Build Your Own Escape Room", he: "בנה את חדר הבריחה שלך", ar: "" },
    build_room_explanation: {
        en: "Use AI to generate unique puzzles and quizzes. Choose from multiple templates and gimmicks to create an unforgettable experience.",
        he: "השתמש ב-AI כדי ליצור חידות וחידונים ייחודיים. בחר מתוך תבניות וגימיקים מרובים כדי ליצור חוויה בלתי נשכחת.",
        ar: "",
    },
    quick_creation: { en: "Quick Creation", he: "יצירה מהירה", ar: "" },
    quick_creation_explanation: {
        en: "Build a complete escape room in minutes with our guided builder",
        he: "בנה חדר בריחה שלם תוך דקות עם הבונה המונחה שלנו",
        ar: "",
    },
    share_publicly: { en: "Share Publicly", he: "שיתוף ציבורי", ar: "" },
    share_publicly_explanation: {
        en: "All escape rooms are free and accessible to everyone",
        he: "כל חדרי הבריחה חינם ונגישים לכולם",
        ar: "",
    },
    ai_powered: { en: "AI-Powered", he: "מופעל על ידי AI", ar: "" },
    ai_powered_explanation: {
        en: "Generate unique content with AI-driven prompts",
        he: "צור תוכן ייחודי עם הנחיות מונחות AI",
        ar: "",
    },
    language: { en: "Language", he: "שפה", ar: "" },
    english: { en: "English", he: "אנגלית", ar: "" },
    hebrew: { en: "Hebrew", he: "עברית", ar: "" },
    // arabic: { en: "Arabic", he: "ערבית", ar: "" },
    room_info: {
        en: "Information for Creating an Escape Room",
        he: "מידע כללי ליצירת חדר בריחה",
        ar: "",
    },
    gen_image: { en: "generate Main Image", he: "יצירת תמונה ראשית", ar: "" },
    create_quizzes: { en: "Create Quizzes", he: "יצירת חידות", ar: "" },
    preview_publish: { en: "Preview & Publish", he: "בדיקה ופרסום", ar: "" },
    eg_first_aid: { en: "e.g. First Aid", he: "דוג' עזרה ראשונה", ar: "" },
    topic: {
        en: "Specific Topic (being detailed and precise is recomended) ",
        he: "נושא ממוקד (מומלץ לפרט ולדייק)",
        ar: "",
    },
    topic_and_data: {
        en: "Topic and Data",
        he: "נושא ונתונים",
        ar: "",
    },
    sub_topic: {
        en: "Sub-topic",
        he: "תת-נושא",
        ar: "",
    },
    enter_topic: {
        en: "Enter the main topic",
        he: "הזן את הנושא הראשי",
        ar: "",
    },
    enter_sub_topic: {
        en: "Enter a sub-topic (optional)",
        he: "הזן תת-נושא (אופציונלי)",
        ar: "",
    },
    upload_document: {
        en: "Upload Document",
        he: "העלה מסמך",
        ar: "",
    },
    click_to_upload: {
        en: "Click to upload",
        he: "לחץ להעלאה",
        ar: "",
    },
    docx_pdf_only: {
        en: "DOCX or PDF files only",
        he: "קבצי DOCX או PDF בלבד",
        ar: "",
    },
    selected_file: {
        en: "Selected:",
        he: "נבחר:",
        ar: "",
    },
    remove: {
        en: "Remove",
        he: "הסר",
        ar: "",
    },
    processing: {
        en: "Processing...",
        he: "מעבד...",
        ar: "",
    },
    clear: {
        en: "Clear",
        he: "נקה",
        ar: "",
    },
    topic_required: {
        en: "Topic is required",
        he: "נושא הוא חובה",
        ar: "",
    },
    file_required: {
        en: "Please select a file",
        he: "אנא בחר קובץ",
        ar: "",
    },
    room_id_required: {
        en: "Room ID is required. Please create a room first.",
        he: "נדרש מזהה חדר. אנא צור חדר תחילה.",
        ar: "",
    },
    document_processed: {
        en: "Document processed successfully",
        he: "המסמך עובד בהצלחה",
        ar: "",
    },
    processing_failed: {
        en: "Failed to process document",
        he: "עיבוד המסמך נכשל",
        ar: "",
    },
    invalid_file_type: {
        en: "Please select a DOCX or PDF file",
        he: "אנא בחר קובץ DOCX או PDF",
        ar: "",
    },
    data_input: {
        en: "Data Input",
        he: "קלט נתונים",
        ar: "",
    },
    upload_file: {
        en: "Upload File",
        he: "העלה קובץ",
        ar: "",
    },
    enter_text: {
        en: "Enter Text",
        he: "הזן טקסט",
        ar: "",
    },
    enter_url: {
        en: "Enter URL",
        he: "הזן כתובת אתר",
        ar: "",
    },
    enter_text_placeholder: {
        en: "Enter or paste your text content here...",
        he: "הזן או הדבק את תוכן הטקסט כאן...",
        ar: "",
    },
    text_input_hint: {
        en: "{action} the text content you want to use for generating the escape room",
        he: "{action} את תוכן הטקסט שברצונך להשתמש בו ליצירת חדר הבריחה",
        ar: "",
    },
    url_input_hint: {
        en: "Enter a URL to extract content from a webpage",
        he: "הזן כתובת אתר לחילוץ תוכן מדף אינטרנט",
        ar: "",
    },
    text_required: {
        en: "Please enter text content",
        he: "אנא הזן תוכן טקסט",
        ar: "",
    },
    url_required: {
        en: "Please enter a URL",
        he: "אנא הזן כתובת אתר",
        ar: "",
    },
    url_fetch_failed: {
        en: "Failed to fetch content from URL",
        he: "נכשל בחילוץ תוכן מכתובת האתר",
        ar: "",
    },
    invalid_url: {
        en: "Please enter a valid URL (e.g., https://example.com)",
        he: "אנא הזן כתובת אתר תקינה (למשל, https://example.com)",
        ar: "",
    },
    room_name: { en: "Room name", he: "שם החדר בריחה", ar: "" },
    name: { en: "Name", he: "שם", ar: "" },
    room_desc: { en: "Short description for the room", he: "תיאור קצר של החדר בריחה", ar: "" },
    desc: { en: "Description", he: "תיאור", ar: "" },
    style: { en: "Style (quizzes background)", he: "סגנון (רקע החידות)", ar: "" },
    realistic: { en: "Realistic", he: "ראליסטי", ar: "" },
    abstract: { en: "Abstract", he: "אבסרקטי", ar: "" },
    minimalistic: { en: "Minimalistic", he: "מינימליסטי", ar: "" },
    comic: { en: "Comic", he: "קומי", ar: "" },
    vintage: { en: "Vintage", he: "ישן", ar: "" },
    color: { en: "Color Palette", he: "צבעים עיקריים", ar: "" },
    font: { en: "Font", he: "גופן", ar: "" },
    preview: { en: "Preview", he: "תצוגה מקדימה", ar: "" },
    saving: { en: "Saving...", he: "שומר...", ar: "" },
    creating_room: { en: "Creating an Escape Room", he: "יצירת חדר בריחה", ar: "" },
    creating_new_room: { en: "Creating New Room", he: "יצירת חדר חדש", ar: "" },
    editing_room: { en: "Editing Room", he: "עריכת חדר", ar: "" },
    viewing_room: { en: "Viewing Room", he: "צפייה בחדר", ar: "" },
    choose_room_type: { en: "Choose Room Type", he: "בחר סוג לחדר בריחה", ar: "" },
    room_type: { en: "Room Type", he: "סוג חדר בריחה", ar: "" },
    personal: {
        en: "Personale (on a personal topics)",
        he: "אישי (מתייחס לנושא אישי/פרטי)",
        ar: "",
    },
    educational: {
        en: "Educational (on genaral knolage topics)",
        he: "חינוכי/הדרכתי (מתייחס לנושאים כללים/נלמדים)",
        ar: "",
    },
    mandatory_field: { en: "Mandatory Input Field", he: "שדה חובה", ar: "" },
    clear_draft: { en: "Clear Draft", he: "אפס את התשובות", ar: "" },
    my_rooms: { en: "My Escape Rooms", he: "חדרי הבריחה שלי", ar: "" },
    edit: { en: "Edit", he: "ערוך", ar: "" },
    share: { en: "Share", he: "שתף", ar: "" },
    delete: { en: "Delete", he: "מחק", ar: "" },
    publish: { en: "Publish (turn to Public)", he: "פרסם (הפוך לציבורי)", ar: "" },
    unpublish: { en: "UnPublish (turn to Private)", he: "הסתר (הפוך לפרטי)", ar: "" },
    public: { en: "Escape room is Public", he: "החדר בריחה ציבורי", ar: "" },
    private: { en: "Escape room is Private", he: "החדר בריחה פרטי", ar: "" },
    room_progress: { en: "Escape room Progress", he: "התקדמות בחדר בריחה", ar: "" },
    reset: { en: "Reset", he: "איפוס", ar: "" },
    current_objective: { en: "Current Objective:", he: "משימה נוכחית:", ar: "" },
    find_quiz_num: { en: "Find Quiz #", he: "מצא חידה #", ar: "" },
    room_field: { en: "Field of Studies", he: "תחום לימודים עיקרי", ar: "" },
    choose_room_field: { en: "Choose Field of Studies", he: "בחר תחום לימודים עיקרי", ar: "" },
    main_background_image: { en: "Main Background Image", he: "תמונת רקע מסך ראשי", ar: "" },
    interesting_insights: { en: "Interesting Insights", he: "תובנות מעניינות", ar: "" },
    explanation: { en: "Explanation", he: "הסבר", ar: "" },
    example: { en: "", he: "", ar: "" },
    // Navigation
    home: { en: "Home", he: "ראשי", ar: "" },
    examples: { en: "Examples", he: "דוגמאות", ar: "" },
    prices: { en: "Prices", he: "מחירים", ar: "" },
    about: { en: "About", he: "אודות", ar: "" },
    create_escape_room: { en: "Create Escape Room", he: "צור חדר בריחה", ar: "" },
    // Hero Section
    hero_title: {
        en: "Turn every subject into an adventure: Create an online escape room tailored to you",
        he: "הפכו כל נושא להרפתקה: צרו חדר בריחה מקוון בהתאמה אישית",
        ar: "",
    },
    hero_subtitle: {
        en: "An intuitive platform for creating learning and team-building experiences, no technical knowledge required.",
        he: "פלטפורמה אינטואיטיבית ליצירת חוויות למידה וגיבוש, ללא צורך בידע טכני.",
        ar: "",
    },
    start_creating_free: { en: "Start creating for free", he: "התחל ליצור בחינם", ar: "" },
    // Game Cards
    my_recent_games: { en: "My Recent Games", he: "המשחקים האחרונים שלי", ar: "" },
    play_now: { en: "Play now", he: "שחק עכשיו", ar: "" },
    // edit: { en: "Edit", he: "ערוך", ar: "" },
    // Footer
    easy_to_use: { en: "Easy to use", he: "קל לשימוש", ar: "" },
    full_customization: { en: "Full customization", he: "התאמה אישית מלאה", ar: "" },
    mobile_adapted: { en: "Mobile adapted", he: "מותאם למובייל", ar: "" },
    // Emergency Protocol Display
    emergency_protocol: {
        en: "Emergency Protocol: ",
        he: "פרוטוקול חירום: ",
        ar: "",
    },
    emergency_protocol_instruction: {
        en: "Instruction: Break into the {count} locked elements",
        he: "הנחיה: פירצו את {count} המוקדים הנעולים",
        ar: "",
    },
    last_played: { en: "Stoped played at", he: "המשחק נעצר ב", ar: "" },
    time_left: { en: "Time left", he: "זמן שנותר", ar: "" },
    view_room: { en: "Preview", he: "תצוגה מקדימה", ar: "" },
    room_not_found: { en: "Room data not found", he: "נתוני החדר לא נמצאו", ar: "" },
    join_our_community: { en: "Join Our Community", he: "הצטרפו לקהילתנו", ar: "" },
    get_free_escape_room: { en: "Get Free Escape Room", he: "קבלו חדר בריחה חינמי", ar: "" },
    contact_support: { en: "Contact Support", he: "יצירת קשר", ar: "" },
    subscribe_to_delete_room: { en: "Subscribe to delete room", he: "הירשם למחיקת חדר", ar: "" },
    completed_rooms: { en: "Completed Rooms", he: "חדרים שהושלמו", ar: "" },
    draft_rooms: { en: "Draft Rooms", he: "חדרים בתהליך יצירה", ar: "" },
    no_quiz_found: { en: "No quiz found", he: "לא נמצאה חידה", ar: "" },
    no_room_found: { en: "No escape room found", he: "לא נמצא חדר בריחה", ar: "" },
    no_subtopics_found: {
        en: "No subtopics found. Please add more text to the document, or try a different topic to define the topic with more presision.",
        he: "לא נמצאו תתי-נושאים. אנא הוסיפו יותר טקסט למסמך, או נסו להגדיר את הנושא בפרטים מדוייקים יותר.",
        ar: "",
    },
    failed_to_create_room: {
        en: "Failed to create room. Please try again.",
        he: "יצירת החדר נכשלה. אנא נסה שנית.",
        ar: "",
    },
    create_quiz_failed: {
        en: "Failed to create quiz. Please try again.",
        he: "יצירת חידה נכשלה. אנא נסה שנית.",
        ar: "",
    },
    not_enough_quizzes: {
        en: "Not enough quizzes. Please create at least 4 quizzes.",
        he: "לא נמצאו מספיק חידות. אנא צור לפחות 4 חידות.",
        ar: "",
    },
    physical_object_selection: {
        en: "Physical Object Selection {quiz_of}",
        he: "{quiz_of} בחירת עצמים פיזיים",
        ar: "",
    },
    event_to_category_matching: {
        en: "Category to Event Matching {quiz_of}",
        he: "{quiz_of} התאמת קטגוריה לאירוע",
        ar: "",
    },
    logical_or_chronological_ordering: {
        en: "Logical or Chronological Ordering {quiz_of}",
        he: "{quiz_of} סדר לוגי או סדר זמני",
        ar: "",
    },
    true_false_fact_questions: {
        en: "True or False Fact Questions {quiz_of}",
        he: "{quiz_of} שאלות נכון או לא נכון",
        ar: "",
    },
    sub_topics: {
        en: "Sub-topics to create quizzes from",
        he: "תתי-נושאים ליצירת חידות מהם",
        ar: "",
    },
    created_quizzes: {
        en: "Created Quizzes",
        he: "חידות שנוצרו",
        ar: "",
    },
    create_quiz_about: {
        en: "Create {quiz_type} about",
        he: "יצירת {quiz_type} אודות",
        ar: "",
    },
    show_quiz: {
        en: "Show Quiz",
        he: "הצג חידה",
        ar: "",
    },
    saving_quizzes: {
        en: "Saving Quizzes...",
        he: "שומר חידות...",
        ar: "",
    },
    save_quizzes: {
        en: "Save Quizzes",
        he: "שמור חידות",
        ar: "",
    },
    should_be_completed_in_seconds: {
        en: "Should be completed in {seconds} seconds",
        he: "אמור להסתיים תוך {seconds} שניות",
        ar: "",
    },
    from_the_text: {
        en: "From the Text",
        he: "מהטקסט",
        ar: "",
    },
    enter_answer: {
        en: "Enter Answer",
        he: "הזן תשובה",
        ar: "",
    },
    answer_required: {
        en: "Answer is required",
        he: "נדרשת תשובה",
        ar: "",
    },
    the_quiz_answer: {
        en: "The Quiz Answer",
        he: "התשובה לחידה",
        ar: "",
    },
    answer_limitations: {
        en: "Answer Limitations",
        he: "מגבלות תשובה",
        ar: "",
    },
    "3-4_digits": {
        en: "3-4 digits",
        he: "3-4 ספרות",
        ar: "",
    },
    "3-5_digits_letters": {
        en: "3-5 digits or letters in Hebrew or English",
        he: "3-5 ספרות או אותיות בעברית או באנגלית",
        ar: "",
    },
    "1-3_digits": {
        en: "1-3 digits",
        he: "1-3 ספרות",
        ar: "",
    },
    "2-5_digits": {
        en: "2-5 digits",
        he: "2-5 ספרות",
        ar: "",
    },
    show_sub_topic: {
        en: "Show Sub-topic",
        he: "הצג תת-נושא",
        ar: "",
    },
    used_sub_topic: {
        en: "Used to create quiz",
        he: "נושא שנוצר ממנו חידה",
        ar: "",
    },
    close_all_sub_topics: {
        en: "Close All Sub-topics",
        he: "סגור את כל התתי-נושאים",
        ar: "",
    },
    close_all_quizzes: {
        en: "Close All Quizzes",
        he: "סגור את כל החידות",
        ar: "",
    },
    sub_topics_to_create_quizzes_from: {
        en: "Sub-topics to create quizzes from",
        he: "תתי-נושאים ליצירת חידות",
        ar: "",
    },
    quiz_of: {
        en: " quiz",
        he: "חידת ",
        ar: "",
    },
    show_colors: {
        en: "Show Colors",
        he: "הצג צבעים",
        ar: "",
    },
    hide_colors: {
        en: "Hide Colors",
        he: "הסתר צבעים",
        ar: "",
    },
    login_required: {
        en: "Login Required",
        he: "כניסה נדרשת",
        ar: "",
    },
    login_to_access_room_builder: {
        en: "Please login to access the Room Builder",
        he: "אנא התחברו לכניסה ליצירת חדר בריחה",
    },
    coming_soon: {
        en: "Coming Soon",
        he: "בקרוב",
        ar: "",
    },
    generate_content: {
        en: "Generate Content",
        he: "ג'ינרוט תוכן",
        ar: "",
    },
    generate_content_explanation: {
        en: `Generating content with AI: Notice that there is no warranty on the accuracy of the content. You can edit the content after the generation and it is recommended to review the content.`,
        he: `ג'ינרוט תוכן עם בינה מלאכותית: שימו לב שאין אחריות על מהימנות התוכן. תתאפשר עריכת התוכן לאחר הג'ינרוט וראוי לעבור על התוכן כדי לבדוק אותו.`,
        ar: "",
    },
    generate_title: {
        en: "Generate content with AI",
        he: "ג'ינרוט תוכן עם AI",
        ar: "",
    },
    more_instructions: {
        en: "More Instructions",
        he: "נתונים נוספים ביחס לנושא",
        ar: "",
    },
    enter_more_instructions: {
        en: "Enter more instructions (optional)",
        he: "הזן נתונים נוספים (אופציונלי)",
        ar: "",
    },
    add_to_content: {
        en: "Add to current content",
        he: "הוסף לתוכן הנוכחי",
        ar: "",
    },
};

export const get_text = (name: string, lang: string) => {
    return appContext[name]
        ? appContext[name][lang]
            ? appContext[name][lang]
            : appContext[name]["en"]
        : name;
};
