interface TranslationEntry {
    [key: string]: string;
}
export interface Translations {
    [key: string]: TranslationEntry;
}

const appContext: Translations = {
    welcome: { en: "Welcome", he: "ברוכים הבאים", ar: "" },
    hello: { en: "Hello", he: "שלום", ar: "" },
    loading: { en: "Loading...", he: "טוען...", ar: "" },
    sign_out: { en: "Sign Out", he: "התנתק", ar: "" },
    next_page: { en: "Next Page", he: "לעמוד הבא", ar: "" },
    no_next_page: { en: "No Next Page", he: "אין עמוד הבא", ar: "" },
    prev_page: { en: "Previous Page", he: "לעמוד הקודם", ar: "" },
    no_prev_page: { en: "No Previous Page", he: "אין עמוד הקודם", ar: "" },
    back_to_main: { en: "Back to main room", he: "חזרה לחדר הראשי", ar: "" },
    success: { en: "Success!", he: "הצלחה!", ar: "" },
    wrong: { en: "Wrong answer... Try again", he: "טעות... נסו שוב", ar: "" },
    continue: { en: "Your getting there... Continue", he: "אתם בדרך הנכונה... המשיכו", ar: "" },
    finish: { en: "Finish", he: "לסיום", ar: "" },
    answer_quiz: { en: "Enter Quiz Answer", he: "מלא תשובה לחידה", ar: "" },
    close: { en: "Close", he: "סגירה", ar: "" },
    close_quiz: { en: "Close Quiz", he: "סגירת חידה", ar: "" },
    check_answer: { en: "Check Answer", he: "בדיקת התשובה", ar: "" },
    more_info: { en: "More Info", he: "מידע נוסף", ar: "" },
    phone_on_side: {
        en: "Please turn your phone on its side",
        he: "אנא סובבו את מכשיר הסלולארי שלכם על צידו",
        ar: "",
    },
    give_hint: { en: "Yes, please give me a hint...", he: "כן, אשמח לקבל רמז בבקשה...", ar: "" },
    get_hint: { en: "Get Hints", he: "קבלו רמזים", ar: "" },
    close_hint: { en: "Close Hints", he: "סגור רמזים", ar: "" },
    do_want_hint: { en: "Do you want a hint?", he: "האם תרצה/י רמז?", ar: "" },
    do_want_another_hint: { en: "Do you want another hint?", he: "האם תרצה/י רמז נוסף?", ar: "" },
    cant_help_more: {
        en: "Sorry, I can't help you any more...",
        he: "מחילה, לא אוכל לעזור לך יותר...",
        ar: "",
    },
    you_can_do_it: {
        en: "Try using the hints I already gave you. You can do it!!",
        he: "נסה להשתמש ברמזים שכבר נתתי לך. אתה יכול לעשות את זה!!",
        ar: "",
    },
    welcome_hint: {
        en: "Hello!! I can help you with the quiz?",
        he: "שלום! האם אוכל לעזור לך עם החידה?",
        ar: "",
    },
    prepare: { en: "Preparing Riddle", he: "מכין את החידה", ar: "" },
    leave_room: { en: "Leaving The Escape-Room", he: "עזב את החדר", ar: "" },
    are_you_sure: {
        en: "Are you sure you want to leave the escape-room?",
        he: "האם אתה בטוח שברצונך לעזוב את חדר הבריחה?",
        ar: "",
    },
    cancel: { en: "Cancel", he: "ביטול", ar: "" },
    exit_room: { en: "Exit Room", he: "יציאה מהחדר", ar: "" },
    enter_room: { en: "Enter Room", he: "כניסה לחדר", ar: "" },
    sexual_harassment: {
        en: "PreventingSexual Harassment",
        he: "מניעת הטרדות מיניות",
        ar: "",
    },
    first_aid: { en: "First Aid", he: "עזרה ראשונה", ar: "" },
    confirm: { en: "Confirm", he: "אישור", ar: "" },
    fraud: { en: "Embezzlement and fraud", he: "הונאות ומעילות", ar: "" },
    title: { en: "Educational Escape Rooms", he: "חדרי בריחה חינוכיים", ar: "" },
    correct: { en: "Correct ✔️", he: "✔️ נכון", ar: "✔️" },
    incorrect: { en: "Incorrect ❌", he: "❌ לא נכון", ar: "❌" },
    situationAction: {
        en: "Situation & Action",
        he: "מצב ופעולה",
        ar: "الوضع العمل",
    },
    instructions: {
        en: "Instructions: ",
        he: "הוראות: ",
        ar: "تعليمات: ",
    },
    puzzle6_inst: {
        en: "Arrange the images in the correct order",
        he: "סדרו את התמונות בסדר הנכון",
        ar: "",
    },
    room_finished: { en: "Room Completed!", he: "החדר הושלם!", ar: "" },
    new_room: { en: "New Room", he: "חדר חדש", ar: "" },
    subscription: { en: "Subscription", he: "מנוי", ar: "" },
    upgrade: { en: "Upgrade", he: "שדרג", ar: "" },
    edit_profile: { en: "Edit Profile", he: "ערוך פרופיל", ar: "" },
    last_updated: { en: "Last Updated", he: "עודכן לאחרונה", ar: "" },
    created_at: { en: "Date Created", he: "תאריך יצירה", ar: "" },
    build_room: { en: "Build Your Own Escape Room", he: "בנה את חדר הבריחה שלך", ar: "" },
    build_room_explanation: {
        en: "Use AI to generate unique puzzles and quizzes. Choose from multiple templates and gimmicks to create an unforgettable experience.",
        he: "השתמש ב-AI כדי ליצור חידות וחידונים ייחודיים. בחר מתוך תבניות וגימיקים מרובים כדי ליצור חוויה בלתי נשכחת.",
        ar: "",
    },
    quick_creation: { en: "Quick Creation", he: "יצירה מהירה", ar: "" },
    quick_creation_explanation: {
        en: "Build a complete escape room in minutes with our guided builder",
        he: "בנה חדר בריחה שלם תוך דקות עם הבונה המונחה שלנו",
        ar: "",
    },
    share_publicly: { en: "Share Publicly", he: "שיתוף ציבורי", ar: "" },
    share_publicly_explanation: {
        en: "All escape rooms are free and accessible to everyone",
        he: "כל חדרי הבריחה חינם ונגישים לכולם",
        ar: "",
    },
    ai_powered: { en: "AI-Powered", he: "מופעל על ידי AI", ar: "" },
    ai_powered_explanation: {
        en: "Generate unique content with AI-driven prompts",
        he: "צור תוכן ייחודי עם הנחיות מונחות AI",
        ar: "",
    },
    language: { en: "Language", he: "שפה", ar: "" },
    english: { en: "English", he: "אנגלית", ar: "" },
    hebrew: { en: "Hebrew", he: "עברית", ar: "" },
    // arabic: { en: "Arabic", he: "ערבית", ar: "" },
    room_info: {
        en: "Information for Creating an Escape Room",
        he: "מידע כללי ליצירת חדר בריחה",
        ar: "",
    },
    gen_image: { en: "generate Main Image", he: "יצירת תמונה ראשית", ar: "" },
    create_quizzes: { en: "Create Quizzes", he: "יצירת חידות", ar: "" },
    preview_publish: { en: "Preview & Publish", he: "בדיקה ופרסום", ar: "" },
    eg_first_aid: { en: "e.g. First Aid", he: "דוג' עזרה ראשונה", ar: "" },
    topic: {
        en: "Specific Topic (being detailed and precise is recomended) ",
        he: "נושא ממוקד (מומלץ לפרט ולדייק)",
        ar: "",
    },
    room_name: { en: "Room name", he: "שם החדר בריחה", ar: "" },
    name: { en: "Name", he: "שם", ar: "" },
    room_desc: { en: "Short description for the room", he: "תיאור קצר של החדר בריחה", ar: "" },
    desc: { en: "Description", he: "תיאור", ar: "" },
    style: { en: "Style (quizzes background)", he: "סגנון (רקע החידות)", ar: "" },
    realistic: { en: "Realistic", he: "ראליסטי", ar: "" },
    abstract: { en: "Abstract", he: "אבסרקטי", ar: "" },
    minimalistic: { en: "Minimalistic", he: "מינימליסטי", ar: "" },
    comic: { en: "Comic", he: "קומי", ar: "" },
    vintage: { en: "Vintage", he: "ישן", ar: "" },
    color: { en: "Color Palette", he: "צבעים עיקריים", ar: "" },
    font: { en: "Font", he: "גופן", ar: "" },
    preview: { en: "Preview", he: "תצוגה מקדימה", ar: "" },
    saving: { en: "Saving...", he: "שומר...", ar: "" },
    creating_room: { en: "Creating an Escape Room", he: "יצירת חדר בריחה", ar: "" },
    choose_room_type: { en: "Choose Room Type", he: "בחר סוג לחדר בריחה", ar: "" },
    room_type: { en: "Room Type", he: "סוג חדר בריחה", ar: "" },
    personal: {
        en: "Personale (on a personal topics)",
        he: "אישי (מתייחס לנושא אישי/פרטי)",
        ar: "",
    },
    educational: {
        en: "Educational (on genaral knolage topics)",
        he: "חינוכי/הדרכתי (מתייחס לנושאים כללים/נלמדים)",
        ar: "",
    },
    mandatory_field: { en: "Mandatory Input Field", he: "שדה חובה", ar: "" },
    clear_draft: { en: "Clear Draft", he: "אפס את התשובות", ar: "" },
    my_rooms: { en: "My Escape Rooms", he: "חדרי הבריחה שלי", ar: "" },
    edit: { en: "Edit", he: "ערוך", ar: "" },
    share: { en: "Share", he: "שתף", ar: "" },
    delete: { en: "Delete", he: "מחק", ar: "" },
    publish: { en: "Publish (turn to Public)", he: "פרסם (הפוך לציבורי)", ar: "" },
    unpublish: { en: "UnPublish (turn to Private)", he: "הסתר (הפוך לפרטי)", ar: "" },
    public: { en: "Escape room is Public", he: "החדר בריחה ציבורי", ar: "" },
    private: { en: "Escape room is Private", he: "החדר בריחה פרטי", ar: "" },
    room_progress: { en: "Escape room Progress", he: "התקדמות בחדר בריחה", ar: "" },
    current_objective: { en: "Current Objective:", he: "משימה נוכחית:", ar: "" },
    find_quiz_num: { en: "Find Quiz #", he: "מצא חידה #", ar: "" },
    room_field: { en: "Field of Studies", he: "תחום לימודים עיקרי", ar: "" },
    choose_room_field: { en: "Choose Field of Studies", he: "בחר תחום לימודים עיקרי", ar: "" },
    main_background_image: { en: "Main Background Image", he: "תמונת רקע מסך ראשי", ar: "" },
    interesting_insights: { en: "Interesting Insights", he: "תובנות מעניינות", ar: "" },
    explanation: { en: "Explanation", he: "הסבר", ar: "" },
    example: { en: "", he: "", ar: "" },
    // Navigation
    home: { en: "Home", he: "ראשי", ar: "" },
    examples: { en: "Examples", he: "דוגמאות", ar: "" },
    prices: { en: "Prices", he: "מחירים", ar: "" },
    about: { en: "About", he: "אודות", ar: "" },
    create_escape_room: { en: "Create Escape Room", he: "צור חדר בריחה", ar: "" },
    // Hero Section
    hero_title: {
        en: "Turn every subject into an adventure: Create an online escape room tailored to you",
        he: "הפכו כל נושא להרפתקה: צרו חדר בריחה מקוון בהתאמה אישית",
        ar: "",
    },
    hero_subtitle: {
        en: "An intuitive platform for creating learning and team-building experiences, no technical knowledge required.",
        he: "פלטפורמה אינטואיטיבית ליצירת חוויות למידה וגיבוש, ללא צורך בידע טכני.",
        ar: "",
    },
    start_creating_free: { en: "Start creating for free", he: "התחל ליצור בחינם", ar: "" },
    // Game Cards
    my_recent_games: { en: "My Recent Games", he: "המשחקים האחרונים שלי", ar: "" },
    play_now: { en: "Play now", he: "שחק עכשיו", ar: "" },
    // edit: { en: "Edit", he: "ערוך", ar: "" },
    // Footer
    easy_to_use: { en: "Easy to use", he: "קל לשימוש", ar: "" },
    full_customization: { en: "Full customization", he: "התאמה אישית מלאה", ar: "" },
    mobile_adapted: { en: "Mobile adapted", he: "מותאם למובייל", ar: "" },
};

export const get_text = (name: string, lang: string) => {
    return appContext[name]
        ? appContext[name][lang]
            ? appContext[name][lang]
            : appContext[name]["en"]
        : name;
};
