const data = {
    _id: "kjbhdfvksjdf",
    name: "Basic First Aid",
    mainImage: "imageURL",
    quiz: [
        {
            _id: "1",
            type: "7segments",
            answer: 1234,
            quizImg: "imageURL",
            quizText: "imageURL",
            quizData: ["imageURL"],
            correctOptions: ["correct1", "correct2", "correct3", "correct4"],
            inCorrectOptions: ["incorrect1", "incorrect2", "incorrect3", "incorrect4"],
            hints: ["firstHint", "secondHint", "thirdHint", "forthHint", "fifthHint"],
        },
        {
            _id: "2",
            type: "gridPlay",
            answer: 125,
            quizImg: "imageURL",
            quizText: "imageURL",
            quizData: ["imageURL"],
            correctOptions: ["correct1", "correct2", "correct3", "correct4"],
            inCorrectOptions: ["incorrect1", "incorrect2", "incorrect3", "incorrect4"],
            hints: ["firstHint", "secondHint", "thirdHint", "forthHint", "fifthHint"],
        },
        {
            _id: "3",
            type: "gridPlay",
            answer: 1234,
            quizImg: "imageURL",
            quizText: "imageURL",
            quizData: ["imageURL"],
            correctOptions: ["correct1", "correct2", "correct3", "correct4"],
            inCorrectOptions: ["incorrect1", "incorrect2", "incorrect3", "incorrect4"],
            hints: ["firstHint", "secondHint", "thirdHint", "forthHint", "fifthHint"],
        },
        {
            _id: "4",
            type: "gridPlay",
            answer: 1234,
            quizImg: "imageURL",
            quizText: "imageURL",
            quizData: ["imageURL"],
            correctOptions: ["correct1", "correct2", "correct3", "correct4"],
            inCorrectOptions: ["incorrect1", "incorrect2", "incorrect3", "incorrect4"],
            hints: ["firstHint", "secondHint", "thirdHint", "forthHint", "fifthHint"],
        },
    ],
};
export default data;
